import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout/Layout";
import styles from "../styles/Resume.module.scss";

export function Resume(props: NextPage) {
  return (
    <>
      <Head>
        <title>Resume</title>
        <meta name="description" content="My actual CV" />
      </Head>
      <Layout>
        <div className="container">
          <h1>Resume</h1>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, explicabo aliquid? Laboriosam, eaque suscipit molestias voluptas optio neque, explicabo error dolore laudantium atque labore a facilis nulla quod temporibus accusamus?</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, explicabo aliquid? Laboriosam, eaque suscipit molestias voluptas optio neque, explicabo error dolore laudantium atque labore a facilis nulla quod temporibus accusamus?</p>
        </div>
      </Layout>
    </>
  );
}

// const Resume: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>My Resume | Balanco Andrei Front-end Developer</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Get my <a href="https://nextjs.org">Resume!</a>
//         </h1>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

export default Resume;
